# Piezo microphone

[Main]
<<<<<<< HEAD
audio_path = "Data/Ti81_end.flac"
=======
audio_path = "Data/Ti81.wav"
>>>>>>> 853a7fe9dac62f4139e801e435312cee645138fa
filtered_audio_directory = "Audio_Filtered/"

[Filter]
max_length = 5
cutoff_low = 350 # Hz
cutoff_high = 6800
minimum_attenuation = 25 # dB
order = 8

[Convolve]
time_short = 30
time_long = 360
time_smooth = 30

[Mask]
threshold_minimum_time = 500 #ms
threshold_overlap_min = 30 # ms
maxZeros = 100

threshold_amplitude_min = 400
threshold_amplitude_max = 10000
threshold_mask_val = 30
threshold_maximum_length = 1

extension_length = 50
